### ISSUE TITLE
copy translated text to clipboard

### ISSUE THREAD

**Issue by bbelderbos** [bbelderbos/italki-class-assistant#2]
This could be handy when you want to use the translated text directly in written comms, could be a checkbox.

**Comment by Owen-Dechow** [comment]
I handle this problem.

**Comment by bbelderbos** [comment]
Nice, thanks, I recommend using this module: https://pypi.org/project/pyperclip/

**Comment by Owen-Dechow** [comment]
> Nice, thanks, I recommend using this module: https://pypi.org/project/pyperclip/

Thanks, that's actually the module I was planning to use.

**Comment by bbelderbos** [comment]
Thanks for already submitting it, how did you hear about the project, was it from our newsletter?
