### ISSUE TITLE
Installation Guid on README.md

### ISSUE THREAD

**Issue by Owen-Dechow** [bbelderbos/italki-class-assistant#6]
The Installation guid in the `README.md` file was missed the db setup. I couldn't figure out the problem until I saw the
`if __name__ == "__main__"` line and ran the `db.py` file out of curiosity.

**Comment by bbelderbos** [comment]
Forgot to update it, thanks for your contributions here. Are you using the tool yourself? Any other features you would like to see @Owen-Dechow ?

**Comment by Owen-Dechow** [comment]
> Forgot to update it, thanks for your contributions here. Are you using the tool yourself? Any other features you would like to see @Owen-Dechow ?

I've used it a little for Spanish, I just find it easier than pulling up google translate in a webbrowser just to look up a single word that i'll probably never use again.
No, I can't think of any features I would want to see added, I think it's the simplicity of the app that makes it so useful.

**Comment by bbelderbos** [comment]
Awesome thanks for confirming.
Indeed you can use the Google site, but I like the little window and that it keeps the persistence. 
We'll have more feature requests as we use it more ... :)
Did you hear about it via our newsletter or via another channel? 
Thanks for jumping in so quickly!

**Comment by Owen-Dechow** [comment]
I actually just stumbled across the repo.

**Comment by bbelderbos** [comment]
Amazing, here on GitHub?
